### ISSUE TITLE
Partial matching issue with `pkg$author`

### ISSUE THREAD

**Issue by jimhester** [ropensci/spelling#2]
https://github.com/ropensci/spelling/blob/7f5e3f6904508ea42d61e7f3c0af2d866e7e5517/R/spell-check.R#L33

will return the `author@R` term if `author` does not exist due to partial matching of `$`. This should be changed to `pkg[["author"]]` and additional code added to parse the `author@R` separately.

**Comment by jeroen** [comment]
Can I parse any field that is postfixed with `@R` using `parse(text = field)` ?

**Comment by jeroen** [comment]
Read your comment too late, I've already implemented it myself now. I think `eval(parse())` works fine in this case, because we're only using the author field to add it to the ignore list.
