### ISSUE TITLE
spell_check_files: FOUND IN file name is mixed up when path isn't sorted

### ISSUE THREAD

**Issue by kylebmetrum** [ropensci/spelling#20]
I put `MistakeA` in `fileA.txt` and `MistakeB` in `fileB.txt`.  When 

```r
path <- c("fileB.txt", "fileA.txt")
```
then `spell_check_files(path)` says `MistakeA` is found in `fileB.txt` and vice versa

``` r


library(spelling)
```

### Create `fileA.txt` and `fileB.txt`

``` r
fileA <- '
store
car
MistakeA
road
'

fileB <- '
store
MistakeB
desk
road
'

writeLines(fileA, con = "fileA.txt")
writeLines(fileB, con = "fileB.txt")


files <- c("fileB.txt", "fileA.txt")
```

### Check each file separately - `FOUND IN` is correct

``` r
l1 <- lapply(files, spell_check_files)
do.call("rbind", l1)
#>   WORD       FOUND IN
#> MistakeB   fileB.txt:3
#> MistakeA   fileA.txt:4
```

### Check in one run - `FOUND IN` is mixed up

``` r
spell_check_files(files)
#>   WORD       FOUND IN
#> MistakeA   fileB.txt:4
#> MistakeB   fileA.txt:3
```

### Sort then check in one run - `FOUND IN` is correct

``` r
spell_check_files(sort(files))
#>   WORD       FOUND IN
#> MistakeA   fileA.txt:4
#> MistakeB   fileB.txt:3
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jeroen** [comment]
🤔

**Comment by jeroen** [comment]
Good catch, thanks!!
