### ISSUE TITLE
include .Rd files in spell_check_files 

### ISSUE THREAD

**Issue by gogonzo** [ropensci/spelling#23]
Hi,
is it possible to include checking `.rd` files in `spell_check_files`? Now, `rd` files are checked as plain text, so code objects are also checked for spelling.

I wonder if `spell_check_file_one` could have additional condition:
```
if (grepl(`\.rd$`, path, ignore.case = TRUE) {
  spell_check_file_rd(...)
}
```

**Comment by jeroen** [comment]
Are you aware that `spell_check_package` automatically checks all rd files in the `man` dir?

**Comment by gogonzo** [comment]
Yes I'm aware.
Cause of my issue is that I've tried to run spell checking for each files seperately. This would allow run test parallelly and see in testthat output how many times `spell_check_files` run (how many files has been tested).

**Comment by jeroen** [comment]
Yeah I guess that makes sense. I think we just need to add `spell_check_file_rd` to this function: https://github.com/ropensci/spelling/blob/master/R/check-files.R#L32-L50. Can you make a pr and test it?

**Comment by gogonzo** [comment]
sure

**Comment by gogonzo** [comment]
thanks 👍
