### ISSUE TITLE
Ignore fancy quotes

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/spelling#43]
I have this in an Rmd:
```
See ['Configuration'][pkg_config] for details.
```
which will have fancy quotes in the `README.md`, courtesy of pandoc I guess:
```
See [‘Configuration’](TODO) for details.
```
and then spellcheck reports:
```
Configuration’ README.md:177
```
I wonder if it would be easy to ignore the fancy quotes? TBH I am not sure why they are considered to be part of the word.

**Comment by jeroen** [comment]
Unfortunately, the ' is specifically not ignored in the English hunspell dictionaries because it is needed for words like it's or let's. It is the only non letter that is allowed in English words, everything else gets ignored.

**Comment by gaborcsardi** [comment]
OK, that makes sense. Apparently Unicode prefer to use `\u2019` for apostrophe, and pandoc uses it for quoted words, so this might be a pandoc error. Although I am not sure what pandoc could use instead. Maybe I should just ignore `README.md` for spellchecking, it is a generated file, anyway.
