### ISSUE TITLE
spell_check_test causes warning inside codecov inside GitHub actions

### ISSUE THREAD

**Issue by and3k** [ropensci/spelling#50]
Hi! :)

I am using [a GitHub action from r-lib to run covr on my code](https://github.com/r-lib/actions/blob/master/examples/test-coverage.yaml). Since I added a `spell_check_test` (using `usethis::use_spell_check`), I get a warning in the covr GitHub action log:

```
files differ in number of lines:
6,8c6
< Warning message:
< In spelling::spell_check_test(error = TRUE) :
<   Failed to find package source directory
```

I get no warnings when I run covr locally. It also runs without a warning in the R CMD check GitHub action.

Example commit: https://github.com/and3k/dtutils/runs/564517180 (see "Test coverage" step)

Thanks!
Bela

**Comment by jefferys** [comment]
I'm having a similar problem. If I run coverage testing with covr::package_coverage(), it runs fine, until I set NOT_CRAN. Then I get the above warning message. Maybe this is some kind of interaction between how covr installs a package for testing and the structure that spelling expects?

```
Sys.setenv(NOT_CRAN="")
covr::package_coverage()
#> RnaSeqDiffExp Coverage: 95.24%
#> ...

Sys.setenv(NOT_CRAN="true")
covr::package_coverage()
#> 
#> files differ in number of lines:
#> 8,10c8
#> < Warning message:
#> < In spell_check_test(vignettes = TRUE, error = FALSE, skip_on_cran = TRUE) :
#> <   Failed to find package source directory
#> ---
#> > All Done!
#> RnaSeqDiffExp Coverage: 97.62%
#> ...
```

I can just ignore this warning, but it seems like a common thing to want to do, to check coverage manually locally with covr with NOT_CRAN set.

session info output:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3  lazyeval_0.2.2  rex_1.2.0       tools_4.0.3     withr_2.4.1     rstudioapi_0.13 crayon_1.4.1   
[8] covr_3.5.1     
```

**Comment by privefl** [comment]
I get a similar issue (cf. https://github.com/privefl/bigsnpr/runs/5972605746?check_suite_focus=true#step:5:16).

Not sure if this is why my coverage hangs for 6 hours while the other tests run fine.
