### ISSUE TITLE
Request for next release of {spelling}

### ISSUE THREAD

**Issue by ddsjoberg** [ropensci/spelling#53]
Hello! I use the lifecycle package to document functions, and spelling gives a verbose warning that the lifecycle macro is not defined.  This had been documented in https://github.com/ropensci/spelling/issues/42 and fixed last October in pull request https://github.com/ropensci/spelling/pull/44 . Would it be possible to make a release so we don't see the warnings when using the CRAN version of spelling? The issue comes up for me when work with staff inexperienced in package development and the warnings throw them off and they can't figure out what is going on.

Many Thanks!

**Comment by jeroen** [comment]
Yes it is on my to-do list!

**Comment by jeroen** [comment]
Ok this is finally on cran now.
