### ISSUE TITLE
Error in read_xml.raw

### ISSUE THREAD

**Issue by DominiqueMakowski** [ropensci/spelling#58]
Running `spelling::spell_check_test()` fails on the [report package](https://github.com/easystats/report/) with the following error:

```
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  PCDATA invalid Char value 27 [9]
```

I seems like the error comes from the [README.md](https://raw.githubusercontent.com/easystats/report/master/README.md), which indeed contains some special characters like percentages etc.

May I know how is it possible either to skip the spelling of that file, or to skip the problematic characters? Thank you

**Comment by jeroen** [comment]
I think the problem is in:

```
report_sample(iris, group_by = "Species")
# �[34m# Descriptive Statistics
# 
# �[39mVariable 
```

Maybe you can try to remove those`�[34m` and `�[39m`

**Comment by jeroen** [comment]
Is this text auto-generated? By which package? It seems to be embedding control characters in the text

**Comment by DominiqueMakowski** [comment]
Yes, this https://github.com/easystats/report/blob/master/README.md README is generated by [this Rmd](https://github.com/easystats/report/blob/master/README.Rmd) itself using the report package. I cannot find the weird characters you mention above 🤔

**Comment by jeroen** [comment]
They are under the output of `report_sample(iris, group_by = "Species")` in the readme.md

**Comment by DominiqueMakowski** [comment]
Fixed, thanks for your help!
