### ISSUE TITLE
Ensure interactive use for `spell_check_setup`

### ISSUE THREAD

**Issue by jonasfreimuth** [ropensci/spelling#86]
Currently, if `spell_check_setup` is run non-interactively (e.g., during a package setup script like `golem`'s [setup script](https://thinkr-open.github.io/golem/articles/a_start.html)), an error is produced.

```
Rscript -e "spelling::spell_check_setup()"
The following words will be added to the wordlist:
 - Lifecycle
 - README
 - RadiantNet
 - golem
Are you sure you want to update the wordlist?Error in utils::menu(c("Yes", "No")) : 
  menu() cannot be used non-interactively
Calls: <Anonymous> -> update_wordlist -> <Anonymous>
Execution halted
```

As far as I can tell the problem seems to be around here:

https://github.com/ropensci/spelling/blob/46f9f8c1bf7f2a52ef344e50d3508cf2535b9870/R/spell-check.R#L158

Simply adding `confirm = interactive()`, or modyfing `update_wordlist` to warn in case of non-interactive use here

https://github.com/ropensci/spelling/blob/46f9f8c1bf7f2a52ef344e50d3508cf2535b9870/R/wordlist.R#L37

should fix this, in case this is not intended. I understand reviewing the updated wordlist is important for preventing false negative
spelling errors, but to me completely preventing non-interactive use not reasonable for this.

**Comment by jeroen** [comment]
OK I added that
